volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

  production_redis_data: {}
  static_volume: {}



services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
      args:
        MAILGUN_API_KEY: ${MAILGUN_API_KEY}

    image: portfolio_production_django
    pull_policy: never
    volumes:
      - production_django_media:/app/portfolio/media
      - static_volume:/app/staticfiles
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: portfolio_production_postgres
    pull_policy: never
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:6

    volumes:
      - production_redis_data:/data


  celeryworker:
    <<: *django
    image: portfolio_production_celeryworker
    pull_policy: never
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: portfolio_production_celerybeat
    pull_policy: never
    command: /start-celerybeat

  flower:
    <<: *django
    image: portfolio_production_flower
    pull_policy: never
    command: /start-flower

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: portfolio_production_nginx
    pull_policy: never
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
      - static_volume:/usr/share/nginx/static:ro
